//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 09/11/2017 20:26:39
namespace WinInvestmentTracker.Tests.Service
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class OdataClient : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public OdataClient(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Investment> Investments
        {
            get
            {
                if ((this._Investments == null))
                {
                    this._Investments = base.CreateQuery<Investment>("Investments");
                }
                return this._Investments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Investment> _Investments;
        /// <summary>
        /// There are no comments for Factors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InvestmentInfluenceFactor> Factors
        {
            get
            {
                if ((this._Factors == null))
                {
                    this._Factors = base.CreateQuery<InvestmentInfluenceFactor>("Factors");
                }
                return this._Factors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InvestmentInfluenceFactor> _Factors;
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InvestmentGroup> Groups
        {
            get
            {
                if ((this._Groups == null))
                {
                    this._Groups = base.CreateQuery<InvestmentGroup>("Groups");
                }
                return this._Groups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InvestmentGroup> _Groups;
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Region> Regions
        {
            get
            {
                if ((this._Regions == null))
                {
                    this._Regions = base.CreateQuery<Region>("Regions");
                }
                return this._Regions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Region> _Regions;
        /// <summary>
        /// There are no comments for Risks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InvestmentRisk> Risks
        {
            get
            {
                if ((this._Risks == null))
                {
                    this._Risks = base.CreateQuery<InvestmentRisk>("Risks");
                }
                return this._Risks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InvestmentRisk> _Risks;
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInvestments(Investment investment)
        {
            base.AddObject("Investments", investment);
        }
        /// <summary>
        /// There are no comments for Factors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFactors(InvestmentInfluenceFactor investmentInfluenceFactor)
        {
            base.AddObject("Factors", investmentInfluenceFactor);
        }
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGroups(InvestmentGroup investmentGroup)
        {
            base.AddObject("Groups", investmentGroup);
        }
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRegions(Region region)
        {
            base.AddObject("Regions", region);
        }
        /// <summary>
        /// There are no comments for Risks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRisks(InvestmentRisk investmentRisk)
        {
            base.AddObject("Risks", investmentRisk);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"WinInvestmentTracker.Models\" xmlns=\"http://schemas.microsoft.com/ado/" +
                "2009/11/edm\"><EntityType Name=\"Investment\"><Key><PropertyRef Name=\"ID\" /></Key><" +
                "Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Descripti" +
                "on\" Type=\"Edm.String\" /><Property Name=\"Symbol\" Type=\"Edm.String\" /><Property Na" +
                "me=\"ValueProposition\" Type=\"Edm.String\" /><Property Name=\"DesirabilityStatement\"" +
                " Type=\"Edm.String\" /><Property Name=\"InitialInvestment\" Type=\"Edm.Single\" Nullab" +
                "le=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><Propert" +
                "y Name=\"Value\" Type=\"Edm.Single\" Nullable=\"false\" /><NavigationProperty Name=\"Re" +
                "gions\" Relationship=\"WinInvestmentTracker.Models.WinInvestmentTracker_Models_Inv" +
                "estment_Regions_WinInvestmentTracker_Models_Region_RegionsPartner\" ToRole=\"Regio" +
                "ns\" FromRole=\"RegionsPartner\" /><NavigationProperty Name=\"Risks\" Relationship=\"W" +
                "inInvestmentTracker.Models.WinInvestmentTracker_Models_Investment_Risks_WinInves" +
                "tmentTracker_Models_InvestmentRisk_RisksPartner\" ToRole=\"Risks\" FromRole=\"RisksP" +
                "artner\" /><NavigationProperty Name=\"Groups\" Relationship=\"WinInvestmentTracker.M" +
                "odels.WinInvestmentTracker_Models_Investment_Groups_WinInvestmentTracker_Models_" +
                "InvestmentGroup_GroupsPartner\" ToRole=\"Groups\" FromRole=\"GroupsPartner\" /><Navig" +
                "ationProperty Name=\"Factors\" Relationship=\"WinInvestmentTracker.Models.WinInvest" +
                "mentTracker_Models_Investment_Factors_WinInvestmentTracker_Models_InvestmentInfl" +
                "uenceFactor_FactorsPartner\" ToRole=\"Factors\" FromRole=\"FactorsPartner\" /></Entit" +
                "yType><EntityType Name=\"InvestmentInfluenceFactor\"><Key><PropertyRef Name=\"ID\" /" +
                "></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"N" +
                "ame\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm" +
                ".String\" /><Property Name=\"Influence\" Type=\"Edm.String\" /><NavigationProperty Na" +
                "me=\"Investments\" Relationship=\"WinInvestmentTracker.Models.WinInvestmentTracker_" +
                "Models_InvestmentInfluenceFactor_Investments_WinInvestmentTracker_Models_Investm" +
                "ent_InvestmentsPartner\" ToRole=\"Investments\" FromRole=\"InvestmentsPartner\" /></E" +
                "ntityType><EntityType Name=\"InvestmentGroup\"><Key><PropertyRef Name=\"ID\" /></Key" +
                "><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" T" +
                "ype=\"Edm.String\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Na" +
                "me=\"Type\" Type=\"Edm.String\" /><NavigationProperty Name=\"Groups\" Relationship=\"Wi" +
                "nInvestmentTracker.Models.WinInvestmentTracker_Models_InvestmentGroup_Groups_Win" +
                "InvestmentTracker_Models_InvestmentGroup_GroupsPartner\" ToRole=\"Groups\" FromRole" +
                "=\"GroupsPartner\" /><NavigationProperty Name=\"Investments\" Relationship=\"WinInves" +
                "tmentTracker.Models.WinInvestmentTracker_Models_InvestmentGroup_Investments_WinI" +
                "nvestmentTracker_Models_Investment_InvestmentsPartner\" ToRole=\"Investments\" From" +
                "Role=\"InvestmentsPartner\" /></EntityType><EntityType Name=\"Region\"><Key><Propert" +
                "yRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><" +
                "Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Name\" Type=\"Edm." +
                "String\" Nullable=\"false\" /><NavigationProperty Name=\"Investments\" Relationship=\"" +
                "WinInvestmentTracker.Models.WinInvestmentTracker_Models_Region_Investments_WinIn" +
                "vestmentTracker_Models_Investment_InvestmentsPartner\" ToRole=\"Investments\" FromR" +
                "ole=\"InvestmentsPartner\" /></EntityType><EntityType Name=\"InvestmentRisk\"><Key><" +
                "PropertyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Type\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Nav" +
                "igationProperty Name=\"Investments\" Relationship=\"WinInvestmentTracker.Models.Win" +
                "InvestmentTracker_Models_InvestmentRisk_Investments_WinInvestmentTracker_Models_" +
                "Investment_InvestmentsPartner\" ToRole=\"Investments\" FromRole=\"InvestmentsPartner" +
                "\" /></EntityType><Association Name=\"WinInvestmentTracker_Models_Investment_Regio" +
                "ns_WinInvestmentTracker_Models_Region_RegionsPartner\"><End Type=\"WinInvestmentTr" +
                "acker.Models.Region\" Role=\"Regions\" Multiplicity=\"*\" /><End Type=\"WinInvestmentT" +
                "racker.Models.Investment\" Role=\"RegionsPartner\" Multiplicity=\"0..1\" /></Associat" +
                "ion><Association Name=\"WinInvestmentTracker_Models_Investment_Risks_WinInvestmen" +
                "tTracker_Models_InvestmentRisk_RisksPartner\"><End Type=\"WinInvestmentTracker.Mod" +
                "els.InvestmentRisk\" Role=\"Risks\" Multiplicity=\"*\" /><End Type=\"WinInvestmentTrac" +
                "ker.Models.Investment\" Role=\"RisksPartner\" Multiplicity=\"0..1\" /></Association><" +
                "Association Name=\"WinInvestmentTracker_Models_Investment_Groups_WinInvestmentTra" +
                "cker_Models_InvestmentGroup_GroupsPartner\"><End Type=\"WinInvestmentTracker.Model" +
                "s.InvestmentGroup\" Role=\"Groups\" Multiplicity=\"*\" /><End Type=\"WinInvestmentTrac" +
                "ker.Models.Investment\" Role=\"GroupsPartner\" Multiplicity=\"0..1\" /></Association>" +
                "<Association Name=\"WinInvestmentTracker_Models_Investment_Factors_WinInvestmentT" +
                "racker_Models_InvestmentInfluenceFactor_FactorsPartner\"><End Type=\"WinInvestment" +
                "Tracker.Models.InvestmentInfluenceFactor\" Role=\"Factors\" Multiplicity=\"*\" /><End" +
                " Type=\"WinInvestmentTracker.Models.Investment\" Role=\"FactorsPartner\" Multiplicit" +
                "y=\"0..1\" /></Association><Association Name=\"WinInvestmentTracker_Models_Investme" +
                "ntInfluenceFactor_Investments_WinInvestmentTracker_Models_Investment_Investments" +
                "Partner\"><End Type=\"WinInvestmentTracker.Models.Investment\" Role=\"Investments\" M" +
                "ultiplicity=\"*\" /><End Type=\"WinInvestmentTracker.Models.InvestmentInfluenceFact" +
                "or\" Role=\"InvestmentsPartner\" Multiplicity=\"0..1\" /></Association><Association N" +
                "ame=\"WinInvestmentTracker_Models_InvestmentGroup_Groups_WinInvestmentTracker_Mod" +
                "els_InvestmentGroup_GroupsPartner\"><End Type=\"WinInvestmentTracker.Models.Invest" +
                "mentGroup\" Role=\"Groups\" Multiplicity=\"*\" /><End Type=\"WinInvestmentTracker.Mode" +
                "ls.InvestmentGroup\" Role=\"GroupsPartner\" Multiplicity=\"0..1\" /></Association><As" +
                "sociation Name=\"WinInvestmentTracker_Models_InvestmentGroup_Investments_WinInves" +
                "tmentTracker_Models_Investment_InvestmentsPartner\"><End Type=\"WinInvestmentTrack" +
                "er.Models.Investment\" Role=\"Investments\" Multiplicity=\"*\" /><End Type=\"WinInvest" +
                "mentTracker.Models.InvestmentGroup\" Role=\"InvestmentsPartner\" Multiplicity=\"0..1" +
                "\" /></Association><Association Name=\"WinInvestmentTracker_Models_Region_Investme" +
                "nts_WinInvestmentTracker_Models_Investment_InvestmentsPartner\"><End Type=\"WinInv" +
                "estmentTracker.Models.Investment\" Role=\"Investments\" Multiplicity=\"*\" /><End Typ" +
                "e=\"WinInvestmentTracker.Models.Region\" Role=\"InvestmentsPartner\" Multiplicity=\"0" +
                "..1\" /></Association><Association Name=\"WinInvestmentTracker_Models_InvestmentRi" +
                "sk_Investments_WinInvestmentTracker_Models_Investment_InvestmentsPartner\"><End T" +
                "ype=\"WinInvestmentTracker.Models.Investment\" Role=\"Investments\" Multiplicity=\"*\"" +
                " /><End Type=\"WinInvestmentTracker.Models.InvestmentRisk\" Role=\"InvestmentsPartn" +
                "er\" Multiplicity=\"0..1\" /></Association></Schema><Schema Namespace=\"Default\" xml" +
                "ns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Contain" +
                "er\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Investments\" EntityType=\"" +
                "WinInvestmentTracker.Models.Investment\" /><EntitySet Name=\"Factors\" EntityType=\"" +
                "WinInvestmentTracker.Models.InvestmentInfluenceFactor\" /><EntitySet Name=\"Groups" +
                "\" EntityType=\"WinInvestmentTracker.Models.InvestmentGroup\" ";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "/><EntitySet Name=\"Regions\" EntityType=\"WinInvestmentTracker.Models.Region\" /><En" +
                "titySet Name=\"Risks\" EntityType=\"WinInvestmentTracker.Models.InvestmentRisk\" /><" +
                "AssociationSet Name=\"WinInvestmentTracker_Models_Investment_Regions_WinInvestmen" +
                "tTracker_Models_Region_RegionsPartnerSet\" Association=\"WinInvestmentTracker.Mode" +
                "ls.WinInvestmentTracker_Models_Investment_Regions_WinInvestmentTracker_Models_Re" +
                "gion_RegionsPartner\"><End Role=\"RegionsPartner\" EntitySet=\"Investments\" /><End R" +
                "ole=\"Regions\" EntitySet=\"Regions\" /></AssociationSet><AssociationSet Name=\"WinIn" +
                "vestmentTracker_Models_Investment_Risks_WinInvestmentTracker_Models_InvestmentRi" +
                "sk_RisksPartnerSet\" Association=\"WinInvestmentTracker.Models.WinInvestmentTracke" +
                "r_Models_Investment_Risks_WinInvestmentTracker_Models_InvestmentRisk_RisksPartne" +
                "r\"><End Role=\"RisksPartner\" EntitySet=\"Investments\" /><End Role=\"Risks\" EntitySe" +
                "t=\"Risks\" /></AssociationSet><AssociationSet Name=\"WinInvestmentTracker_Models_I" +
                "nvestment_Groups_WinInvestmentTracker_Models_InvestmentGroup_GroupsPartnerSet\" A" +
                "ssociation=\"WinInvestmentTracker.Models.WinInvestmentTracker_Models_Investment_G" +
                "roups_WinInvestmentTracker_Models_InvestmentGroup_GroupsPartner\"><End Role=\"Grou" +
                "psPartner\" EntitySet=\"Investments\" /><End Role=\"Groups\" EntitySet=\"Groups\" /></A" +
                "ssociationSet><AssociationSet Name=\"WinInvestmentTracker_Models_Investment_Facto" +
                "rs_WinInvestmentTracker_Models_InvestmentInfluenceFactor_FactorsPartnerSet\" Asso" +
                "ciation=\"WinInvestmentTracker.Models.WinInvestmentTracker_Models_Investment_Fact" +
                "ors_WinInvestmentTracker_Models_InvestmentInfluenceFactor_FactorsPartner\"><End R" +
                "ole=\"FactorsPartner\" EntitySet=\"Investments\" /><End Role=\"Factors\" EntitySet=\"Fa" +
                "ctors\" /></AssociationSet><AssociationSet Name=\"WinInvestmentTracker_Models_Inve" +
                "stmentInfluenceFactor_Investments_WinInvestmentTracker_Models_Investment_Investm" +
                "entsPartnerSet\" Association=\"WinInvestmentTracker.Models.WinInvestmentTracker_Mo" +
                "dels_InvestmentInfluenceFactor_Investments_WinInvestmentTracker_Models_Investmen" +
                "t_InvestmentsPartner\"><End Role=\"InvestmentsPartner\" EntitySet=\"Factors\" /><End " +
                "Role=\"Investments\" EntitySet=\"Investments\" /></AssociationSet><AssociationSet Na" +
                "me=\"WinInvestmentTracker_Models_InvestmentGroup_Groups_WinInvestmentTracker_Mode" +
                "ls_InvestmentGroup_GroupsPartnerSet\" Association=\"WinInvestmentTracker.Models.Wi" +
                "nInvestmentTracker_Models_InvestmentGroup_Groups_WinInvestmentTracker_Models_Inv" +
                "estmentGroup_GroupsPartner\"><End Role=\"GroupsPartner\" EntitySet=\"Groups\" /><End " +
                "Role=\"Groups\" EntitySet=\"Groups\" /></AssociationSet><AssociationSet Name=\"WinInv" +
                "estmentTracker_Models_InvestmentGroup_Investments_WinInvestmentTracker_Models_In" +
                "vestment_InvestmentsPartnerSet\" Association=\"WinInvestmentTracker.Models.WinInve" +
                "stmentTracker_Models_InvestmentGroup_Investments_WinInvestmentTracker_Models_Inv" +
                "estment_InvestmentsPartner\"><End Role=\"InvestmentsPartner\" EntitySet=\"Groups\" />" +
                "<End Role=\"Investments\" EntitySet=\"Investments\" /></AssociationSet><AssociationS" +
                "et Name=\"WinInvestmentTracker_Models_Region_Investments_WinInvestmentTracker_Mod" +
                "els_Investment_InvestmentsPartnerSet\" Association=\"WinInvestmentTracker.Models.W" +
                "inInvestmentTracker_Models_Region_Investments_WinInvestmentTracker_Models_Invest" +
                "ment_InvestmentsPartner\"><End Role=\"InvestmentsPartner\" EntitySet=\"Regions\" /><E" +
                "nd Role=\"Investments\" EntitySet=\"Investments\" /></AssociationSet><AssociationSet" +
                " Name=\"WinInvestmentTracker_Models_InvestmentRisk_Investments_WinInvestmentTrack" +
                "er_Models_Investment_InvestmentsPartnerSet\" Association=\"WinInvestmentTracker.Mo" +
                "dels.WinInvestmentTracker_Models_InvestmentRisk_Investments_WinInvestmentTracker" +
                "_Models_Investment_InvestmentsPartner\"><End Role=\"InvestmentsPartner\" EntitySet=" +
                "\"Risks\" /><End Role=\"Investments\" EntitySet=\"Investments\" /></AssociationSet></E" +
                "ntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WinInvestmentTracker.Models.Investment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Investments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Investment : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Investment object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="initialInvestment">Initial value of InitialInvestment.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="value">Initial value of Value.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Investment CreateInvestment(int ID, float initialInvestment, string name, float value)
        {
            Investment investment = new Investment();
            investment.ID = ID;
            investment.InitialInvestment = initialInvestment;
            investment.Name = name;
            investment.Value = value;
            return investment;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Symbol in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Symbol
        {
            get
            {
                return this._Symbol;
            }
            set
            {
                this.OnSymbolChanging(value);
                this._Symbol = value;
                this.OnSymbolChanged();
                this.OnPropertyChanged("Symbol");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Symbol;
        partial void OnSymbolChanging(string value);
        partial void OnSymbolChanged();
        /// <summary>
        /// There are no comments for Property ValueProposition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ValueProposition
        {
            get
            {
                return this._ValueProposition;
            }
            set
            {
                this.OnValuePropositionChanging(value);
                this._ValueProposition = value;
                this.OnValuePropositionChanged();
                this.OnPropertyChanged("ValueProposition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ValueProposition;
        partial void OnValuePropositionChanging(string value);
        partial void OnValuePropositionChanged();
        /// <summary>
        /// There are no comments for Property DesirabilityStatement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DesirabilityStatement
        {
            get
            {
                return this._DesirabilityStatement;
            }
            set
            {
                this.OnDesirabilityStatementChanging(value);
                this._DesirabilityStatement = value;
                this.OnDesirabilityStatementChanged();
                this.OnPropertyChanged("DesirabilityStatement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DesirabilityStatement;
        partial void OnDesirabilityStatementChanging(string value);
        partial void OnDesirabilityStatementChanged();
        /// <summary>
        /// There are no comments for Property InitialInvestment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float InitialInvestment
        {
            get
            {
                return this._InitialInvestment;
            }
            set
            {
                this.OnInitialInvestmentChanging(value);
                this._InitialInvestment = value;
                this.OnInitialInvestmentChanged();
                this.OnPropertyChanged("InitialInvestment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _InitialInvestment;
        partial void OnInitialInvestmentChanging(float value);
        partial void OnInitialInvestmentChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _Value;
        partial void OnValueChanging(float value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Region> Regions
        {
            get
            {
                return this._Regions;
            }
            set
            {
                this._Regions = value;
                this.OnPropertyChanged("Regions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Region> _Regions = new global::System.Data.Services.Client.DataServiceCollection<Region>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Risks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvestmentRisk> Risks
        {
            get
            {
                return this._Risks;
            }
            set
            {
                this._Risks = value;
                this.OnPropertyChanged("Risks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvestmentRisk> _Risks = new global::System.Data.Services.Client.DataServiceCollection<InvestmentRisk>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this._Groups = value;
                this.OnPropertyChanged("Groups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup> _Groups = new global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Factors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvestmentInfluenceFactor> Factors
        {
            get
            {
                return this._Factors;
            }
            set
            {
                this._Factors = value;
                this.OnPropertyChanged("Factors");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvestmentInfluenceFactor> _Factors = new global::System.Data.Services.Client.DataServiceCollection<InvestmentInfluenceFactor>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WinInvestmentTracker.Models.InvestmentInfluenceFactor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Factors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class InvestmentInfluenceFactor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new InvestmentInfluenceFactor object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static InvestmentInfluenceFactor CreateInvestmentInfluenceFactor(int ID, string name)
        {
            InvestmentInfluenceFactor investmentInfluenceFactor = new InvestmentInfluenceFactor();
            investmentInfluenceFactor.ID = ID;
            investmentInfluenceFactor.Name = name;
            return investmentInfluenceFactor;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Influence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Influence
        {
            get
            {
                return this._Influence;
            }
            set
            {
                this.OnInfluenceChanging(value);
                this._Influence = value;
                this.OnInfluenceChanged();
                this.OnPropertyChanged("Influence");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Influence;
        partial void OnInfluenceChanging(string value);
        partial void OnInfluenceChanged();
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Investment> Investments
        {
            get
            {
                return this._Investments;
            }
            set
            {
                this._Investments = value;
                this.OnPropertyChanged("Investments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Investment> _Investments = new global::System.Data.Services.Client.DataServiceCollection<Investment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WinInvestmentTracker.Models.InvestmentGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Groups")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class InvestmentGroup : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new InvestmentGroup object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static InvestmentGroup CreateInvestmentGroup(int ID)
        {
            InvestmentGroup investmentGroup = new InvestmentGroup();
            investmentGroup.ID = ID;
            return investmentGroup;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this._Groups = value;
                this.OnPropertyChanged("Groups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup> _Groups = new global::System.Data.Services.Client.DataServiceCollection<InvestmentGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Investment> Investments
        {
            get
            {
                return this._Investments;
            }
            set
            {
                this._Investments = value;
                this.OnPropertyChanged("Investments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Investment> _Investments = new global::System.Data.Services.Client.DataServiceCollection<Investment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WinInvestmentTracker.Models.Region in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Regions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Region : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Region object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Region CreateRegion(int ID, string name)
        {
            Region region = new Region();
            region.ID = ID;
            region.Name = name;
            return region;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Investment> Investments
        {
            get
            {
                return this._Investments;
            }
            set
            {
                this._Investments = value;
                this.OnPropertyChanged("Investments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Investment> _Investments = new global::System.Data.Services.Client.DataServiceCollection<Investment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WinInvestmentTracker.Models.InvestmentRisk in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Risks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class InvestmentRisk : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new InvestmentRisk object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="type">Initial value of Type.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static InvestmentRisk CreateInvestmentRisk(int ID, string type)
        {
            InvestmentRisk investmentRisk = new InvestmentRisk();
            investmentRisk.ID = ID;
            investmentRisk.Type = type;
            return investmentRisk;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Investments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Investment> Investments
        {
            get
            {
                return this._Investments;
            }
            set
            {
                this._Investments = value;
                this.OnPropertyChanged("Investments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Investment> _Investments = new global::System.Data.Services.Client.DataServiceCollection<Investment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
